original-author: 若离|IceTiki|https://github.com/IceTiki/ruoli-sign-optimization
# YAML有引用和锚点，可以节省配置长度(备注:锚点要放在引用的前面)(可以参考https://www.runoob.com/w3cnote/yaml-intro.html)
# ======================================================================
# 全局设置
# ======================================================================
locationOffsetRange: 5 # 坐标偏移范围(单位：米)(可以为0)
maxTry: 1 # 最大尝试次数
logDir: "log/" # 日志保存地址
delay: [1, 2] # 多用户时，各用户之间任务执行延迟(时间范围可以使用浮点数)

captcha: # 图片验证码识别
  tencentSecretId: "" # 腾讯云OCR
  tencentSecretKey: "" # 腾讯云OCR
  captchaLen: 4 # 验证码长度
sendMessage: # 推送函数的整体运行情况(不需要的项目不用填，可以删掉或者放着不管)
  rl_emailApiUrl: http://api.ruoli.cc/mail/sendMail # 邮箱API的地址
  rl_email: "" # email 接受通知消息的邮箱
  iceCream_token: "" # iceCream(若离开发的qq推送)(https://ice.ruoli.cc)
  qmsg_key: "" # qmsg推送的key
  qmsg_qq: "" # qmsg推送的qq号
  qmsg_isGroup: 0 # 此qq号是否为群(是的话填1，反之为0)
  pushplus_parameters: "" # pushplus参数，填入令牌(token)即可推送。也可以填入"token=xxx&topic=xxx"形式自定义更多参数
  pushplus_isNew: False # False使用旧版pushplus(https://pushplus.hxtrip.com)，True使用新版pushplus(https://www.pushplus.plus)
  smtp_host: "smtp.qq.com" # SMTP服务器域名
  smtp_user: "*****@qq.com" # SMTP服务器用户名
  smtp_key: "" # SMTP服务器密钥
  smtp_sender: "*****@qq.com" # 发送邮箱
  smtp_senderName: "发送者名字" # 发送者名字(选填)
  smtp_receivers:
    - "*****@qq.com" # 接收邮箱(可填多个)

# ======================================================================
# 用户组配置(填写自己所需的类型，并删掉不需要的。可以多用户签到。)
# ======================================================================

users: # ------别误删了这一行------
  - # 这个符号 “-” 代表单一用户的配置信息开始，不要误删！
    # 信息收集模板=======
    # 通用必填项-------
    type: 0
    schoolName: 家里蹲大学 # 学校全称 （别忘了修改）
    username: "202202222" # 学号或者工号
    password: "xxxxxxxxxxxxxxxxx" # 密码
    # 一般需填项-------
    signLevel: 1 # 收集任务等级[1:仅填报未填报的任务|2:已填报的任务也重复填报]
    title: 0 # [str:收集任务的标题|0:取最后一个未收集的任务]
    checkTitle: 1 # 是否检查表单的标题（1:检查|0:不检查）
    forms: # 表单信息
      - form:
          title: 是否在“青春湖北”上完成学习 #标题
          value: 是 # 如果是多选请用"|"分割值
          isNeed: 1 # 是否需要提交此问题，必填问题一定要填1(1:提交|0:不提交)
      - form:
          title: 请上传登录界面截图、完成学习截图
          value:
            - /tmp/personal_info.jpg
            - /tmp/finish.jpg
            # 腾讯云函数中临时文件必须放在/tmp目录下
            # 单张图片可这样写: 'info.png'
            # 多张图片就这样:
            # - 1.png
            # - 2.png
            # - ...
          isNeed: 1
    # 经纬度查询地址（请参考自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
    # (特别提醒!!!手机GPS是WGS-84坐标系，普通地图是GCJ02坐标系，今日校园用的是BD09坐标系。不要耍小聪明去其他地方获取坐标)
    lon: 115.000000 # 经度
    lat: 50.000000 # 纬度
    address: "银河系" # 显示在今日校园上的地址信息

    # 青年大学习 （单用户配置）
    openid: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

    # 添加文字配置部分
    add_status_bar: true # 是否给生成的图片添加状态栏
    status_bar_images: # !注意! 不要写成这样 -> /image/x.jpg
      - "image/1_blank.png"
      - "image/2_blank.png"
    add_text: false # 是否给最终图片添加文字
    text: "NoTeenStudy"
    color: "#FFFFFF" # 16进制颜色值
    font: "NotoSansSC.otf" # /font目录下的自定义字体文件名
    text_size: 40
    pos_x: 200
    pos_y: 200
    # 注意此字体同时用于状态栏上的标题生成和截图上另外添加的文本

  - # !!!!!!!!!!配置多用户时不要遗漏这一行("- "代表数组里一项的开始)!!!!!!!!!!
    # 信息收集模板=======
    # 通用必填项-------
    type: 0
    schoolName: 家里蹲大学 # 学校全称
    username: "202202222" # 学号或者工号
    password: "xxxxxxxxxxxxxxxxx" # 密码
    # 一般需填项-------
    signLevel: 1 # 收集任务等级[1:仅填报未填报的任务|2:已填报的任务也重复填报]
    title: 0 # [str:收集任务的标题|0:取最后一个未收集的任务]
    checkTitle: 1 # 是否检查表单的标题（1:检查|0:不检查）
    forms: # 表单信息
      - form:
          title: 是否在“青春湖北”上完成学习 #标题
          value: 是 # 如果是多选请用"|"分割值
          isNeed: 1 # 是否需要提交此问题，必填问题一定要填1(1:提交|0:不提交)
      - form:
          title: 请上传登录界面截图、完成学习截图
          value:
            - /tmp/personal_info.jpg
            - /tmp/finish.jpg
            # 腾讯云函数中临时文件必须放在/tmp目录下
            # 单张图片可这样写: 'info.png'
            # 多张图片就这样:
            # - 1.png
            # - 2.png
            # - ...
          isNeed: 1
    # 经纬度查询地址（请参考自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
    # (特别提醒!!!手机GPS是WGS-84坐标系，普通地图是GCJ02坐标系，今日校园用的是BD09坐标系。不要耍小聪明去其他地方获取坐标)
    lon: 115.000000 # 经度
    lat: 50.000000 # 纬度
    address: "银河系" # 显示在今日校园上的地址信息

    # 青年大学习 （单用户配置）
    openid: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

    # 添加文字配置部分
    add_status_bar: true # 是否给生成的图片添加状态栏
    status_bar_images: # !注意! 不要写成这样 -> /image/x.jpg
      - "image/1_blank.png"
      - "image/2_blank.png"
    add_text: false # 是否给最终图片添加文字
    text: "NoTeenStudy"
    color: "#FFFFFF" # 16进制颜色值
    font: "NotoSansSC.otf" # /font目录下的自定义字体文件名
    text_size: 40
    pos_x: 200
    pos_y: 400
    # 注意此字体同时用于状态栏上的标题生成和截图上另外添加的文本



# ======================================================================
# 全局配置部分 （青年大学习）
# ======================================================================

######## 此处不要修改,仅调试使用 ########
output_dir: "/tmp/"
content_images:
  - "/tmp/finish.jpg"
  - "/tmp/personal_info.jpg"
######## 此处不要修改,仅调试使用 ########

######## 青年大学习图片生成的设定 ########
personal_info_generate_server: "http://124.222.5.227:8080"
token: "xxxxxxxxxxxxxxx" # 网页截屏大师的token